--[[ AUTOGENERATED PLUGIN FILES
--]]

return {
    enabled = {
        'appearance/goolord-alpha_nvim.lua', -- dashboard

        'lsp/autocompletion/hrsh7th-nvim_cmp.lua',
        -- 'lsp/Wansmer-symbol_usage_nvim.lua',
        'lsp/williamboman-mason_lspconfig_nvim.lua',
        'lsp/neovim-nvim_lspconfig.lua',

        'debug/jay_babu-mason_nvim_dap_nvim.lua', -- before second dap
        'debug/rcarriga-nvim_dap_ui.lua',

        'vcs/lewis6991-gitsigns_nvim.lua',
        'vcs/kdheepak-lazygit_nvim.lua',
        -- 'vcs/ludovicchabant-vim_lawrencium.lua',

        -- 'code/Leon_Degel_Koehn-qmlformat_nvim.lua',

        'code/cpp/p00f-clangd_extensions_nvim.lua',
        'code/cpp/nvim_treesitter_cpp_tools.lua',
        'code/cpp/peterhoeg-vim_qml.lua',
        'code/cpp/d86leader-vim_cpp_helper.lua',
        'code/cpp/cdelledonne-vim_cmake.lua',
        
        -- 'code/honza-vim_snippets.lua',
        'code/echasnovski-mini_move.lua',
        'code/lukas_reineke-indent_blankline_nvim.lua',
        -- 'code/Exafunction-codeium_vim.lua',
        'code/HiPhish-rainbow_delimiters_nvim.lua',
        'code/nvim_treesitter-nvim_treesitter.lua',
        'code/mhartington-formatter_nvim.lua',

        'code/numToStr-Comment_nvim.lua',
        'code/kylechui-nvim_surround.lua',
        'code/folke-todo_comments_nvim.lua',

        -- 'navigation/akinsho-bufferline_nvim.lua',
        'navigation/folke-noice_nvim.lua',
        'navigation/folke-trouble_nvim.lua',
        'navigation/folke-flash_nvim.lua',
        'navigation/kevinhwang91-nvim_ufo.lua',
        'navigation/otavioschwanck-arrow_nvim.lua',
        -- 'navigation/gaborvecsei-memento_nvim.lua',
        'navigation/sontungexpt-stcursorword.lua',
        'navigation/folke-which_key_nvim.lua',
        'navigation/nvim_telescope-telescope_nvim.lua',
        'navigation/nvim_lualine-lualine_nvim.lua',
        'navigation/nvim_tree-nvim_tree_lua.lua',
        'navigation/stevearc-aerial_nvim.lua',
        
        -- 'nvim/rmagatti-auto_session.lua',
        'nvim/pocco81-auto_save_nvim.lua',
        -- 'nvim/folke-persistence_nvim.lua',
        'nvim/akinsho-toggleterm_nvim.lua',
        'nvim/folke-edgy_nvim.lua',
        -- 'nvim/gelguy-wilder_nvim.lua',

        'colorscheme/navarasu-onedark_nvim.lua',
    },
    disabled = {
    },
}